# Generated by Django 5.0.1 on 2024-01-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
